### JWT
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NzI1MDg0NTB9.hlybWSMrqCosmavXcu4WChLQ4psZFQSz4o0EFQYNwa4
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test2@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Users Update
PATCH http://localhost:3000/users/1
Content-Type: application/json

{
  "address": "326 S 19th St Philadelphia PA"
}

### Show Trips
GET http://localhost:3000/trips/1
Authorization: Bearer {{jwt}}
Content-Type: application/json

### Create Trip
POST http://localhost:3000/trips
Content-Type: application/json

{
  "user_id": 1,
  "restaurant_id": 1
}